create table answers
(
    id          bigserial not null
        constraint answers_pkey
            primary key,
    code        varchar(255),
    description varchar(255),
    id_father   integer
);

alter table answers
    owner to postgres;

INSERT INTO public.answers (id, code, description, id_father) VALUES (1001, 'mun_136 ', 'Mazatenango ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1002, 'mun_137 ', 'Cuyotenango ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1003, 'mun_138 ', 'San Francisco Zapotitlán ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1004, 'mun_139 ', 'San Bernardino ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1005, 'mun_140 ', 'San José El ídolo ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1006, 'mun_141 ', 'Santo Domingo Suchitepéquez ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1007, 'mun_142 ', 'San Lorenzo ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1008, 'mun_143 ', 'Samayac ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1009, 'mun_144 ', 'San Pablo Jocopilas ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1010, 'mun_145 ', 'San Antonio Suchitepéquez ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1011, 'mun_146 ', 'San Miguel Panán ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1012, 'mun_147 ', 'San Gabriel ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1013, 'mun_148 ', 'Chicacao ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1014, 'mun_149 ', 'Patulul ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1015, 'mun_150 ', 'Santa Bárbara ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1016, 'mun_151 ', 'San Juan Bautista ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1017, 'mun_152 ', 'Santo Tomás La Unión ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1018, 'mun_153 ', 'Zunilito ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1019, 'mun_154 ', 'Pueblo Nuevo ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1020, 'mun_155 ', 'Río Bravo ', 1000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1101, 'mun_156 ', 'Retalhuleu ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1102, 'mun_157 ', 'San Sebastián ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1103, 'mun_158 ', 'Santa Cruz Muluá ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1104, 'mun_159 ', 'San Martín Zapotitlán ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1105, 'mun_160 ', 'San Felipe Retalhuleu ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1106, 'mun_161 ', 'San Andrés Villa Seca ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1107, 'mun_162 ', 'Champerico ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1108, 'mun_163 ', 'Nuevo San Carlos ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1109, 'mun_164 ', 'El Asintal ', 1100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1201, 'mun_165 ', 'San Marcos ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1202, 'mun_166 ', 'San Pedro Sacatepéquez ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1203, 'mun_167 ', 'San Antonio Sacatepéquez ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1204, 'mun_168 ', 'Comitancillo ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1205, 'mun_169 ', 'San Miguel Ixtahuacán ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1206, 'mun_170 ', 'Concepción Tutuapa ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1207, 'mun_171 ', 'Tacaná ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1208, 'mun_172 ', 'Sibinal ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1209, 'mun_173 ', 'Tajumulco ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1210, 'mun_174 ', 'Tejutla ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1211, 'mun_175 ', 'San Rafael Pie de la Cuesta ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1212, 'mun_176 ', 'Nuevo Progreso ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1213, 'mun_177 ', 'El Tumbador ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1214, 'mun_178 ', 'El Rodeo ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1215, 'mun_179 ', 'Malacatán ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1216, 'mun_180 ', 'Catarina ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1217, 'mun_181 ', 'Ayutla ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1218, 'mun_182 ', 'Ocós ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1219, 'mun_183 ', 'San Pablo ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1220, 'mun_184 ', 'El Quetzal ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1221, 'mun_185 ', 'La Reforma ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1222, 'mun_186 ', 'Pajapita ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1223, 'mun_187 ', 'Ixchiguán ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1224, 'mun_188 ', 'San José Ojetenam ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1225, 'mun_189 ', 'San Cristóbal Cucho ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1226, 'mun_190 ', 'Sipacapa ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1227, 'mun_191 ', 'Esquipulas Palo Gordo ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (101, 'mun_1 ', 'Guatemala ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (102, 'mun_2 ', 'Santa Catarina Pinula ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (103, 'mun_3 ', 'San José Pinula ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (104, 'mun_4 ', 'San José del Golfo ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (105, 'mun_5 ', 'Palencia ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (106, 'mun_6 ', 'Chinautla ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (107, 'mun_7 ', 'San Pedro Ayampuc ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (108, 'mun_8 ', 'Mixco ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (109, 'mun_9 ', 'San Pedro Sacatepéquez ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (110, 'mun_10 ', 'San Juan Sacatépequez ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (111, 'mun_11 ', 'San Raymundo ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (112, 'mun_12 ', 'Chuarrancho ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (113, 'mun_13 ', 'Fraijanes ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (114, 'mun_14 ', 'Amatitlán ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (115, 'mun_15 ', 'Villa Nueva ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (116, 'mun_16 ', 'Villa Canales ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (117, 'mun_17 ', 'Petapa ', 100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (201, 'mun_18 ', 'Guastatoya ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (202, 'mun_19 ', 'Morazán ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (203, 'mun_20 ', 'San Agustín Acasaguastlán ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (204, 'mun_21 ', 'San Cristóbal Acasaguastlán ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (205, 'mun_22 ', 'El Jícaro ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (206, 'mun_23 ', 'Sansare ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (207, 'mun_24 ', 'Sanarate ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (208, 'mun_25 ', 'San Antonio La Paz ', 200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (301, 'mun_26 ', 'Antigua Guatemala ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (302, 'mun_27 ', 'Jocotenango ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (303, 'mun_28 ', 'Pastores ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (304, 'mun_29 ', 'Sumpango ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (305, 'mun_30 ', 'Sto. Domingo Xenacoj ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (306, 'mun_31 ', 'Santiago Sacatepéquez ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (307, 'mun_32 ', 'San Bartolomé Millpas Altas ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (308, 'mun_33 ', 'San Lucas Sacatepéquez ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (309, 'mun_34 ', 'Santa Lucia Milpas Altas ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (310, 'mun_35 ', 'Magdalena Milpas Altas ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (311, 'mun_36 ', 'Santa María de Jesús ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (312, 'mun_37 ', 'Ciudad Vieja ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (313, 'mun_38 ', 'San Miguel Dueñas ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (314, 'mun_39 ', 'Alotenango ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (315, 'mun_40 ', 'San Antonio Aguas Calientes ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (316, 'mun_41 ', 'Santa Catarina Barahona ', 300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (401, 'mun_42 ', 'Chimaltenango ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (402, 'mun_43 ', 'San José Poaquil ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (403, 'mun_44 ', 'San Martín Jilotepeque ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (404, 'mun_45 ', 'Comalapa ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (405, 'mun_46 ', 'Santa Apolonia ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (406, 'mun_47 ', 'Tecpán Guatemala ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (407, 'mun_48 ', 'Patzún ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (408, 'mun_49 ', 'Pochuta ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (409, 'mun_50 ', 'Patzicia ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (410, 'mun_51 ', 'Santa Cruz Balanyá ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (411, 'mun_52 ', 'Acatenango ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (412, 'mun_53 ', 'Yepocapa ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (413, 'mun_54 ', 'San Andrés Iztapa ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (414, 'mun_55 ', 'Parramos ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (415, 'mun_56 ', 'Zaragoza ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (416, 'mun_57 ', 'El Tejar ', 400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (501, 'mun_58 ', 'Escuintla ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (502, 'mun_59 ', 'Santa Lucía Cotzumalguapa ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (503, 'mun_60 ', 'La Democracia ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (504, 'mun_61 ', 'Siquinalá ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (505, 'mun_62 ', 'Masagua ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (506, 'mun_63 ', 'Tiquisate ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (507, 'mun_64 ', 'La Gomera ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (508, 'mun_65 ', 'Guanagazapa ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (509, 'mun_66 ', 'San José ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (510, 'mun_67 ', 'Iztapa ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (511, 'mun_68 ', 'Palín ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (512, 'mun_69 ', 'San Vicente Pacaya ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (513, 'mun_70 ', 'Nueva Concepción ', 500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (601, 'mun_71 ', 'Cuilapa ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (602, 'mun_72 ', 'Barberena ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (603, 'mun_73 ', 'Santa Rosa de Lima ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (604, 'mun_74 ', 'Casillas ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (605, 'mun_75 ', 'San Rafael Las Flores ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (606, 'mun_76 ', 'Oratorio ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (607, 'mun_77 ', 'San Juan Tecuaco ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (608, 'mun_78 ', 'Chiquimulilla ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (609, 'mun_79 ', 'Taxisco ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (610, 'mun_80 ', 'Santa María Ixhuatán ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (611, 'mun_81 ', 'Guazacapán ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (612, 'mun_82 ', 'Santa Cruz Naranjo ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (613, 'mun_83 ', 'Pueblo Nuevo Viñas ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (614, 'mun_84 ', 'Nueva Santa Rosa ', 600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (701, 'mun_85 ', 'Sololá ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (702, 'mun_86 ', 'San José Chacayá ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (703, 'mun_87 ', 'Santa María Visitación ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (704, 'mun_88 ', 'Santa Lucía Utatlán ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (705, 'mun_89 ', 'Nahualá ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (706, 'mun_90 ', 'Santa Catarina Ixtahuacán ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (707, 'mun_91 ', 'Santa Clara La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (708, 'mun_92 ', 'Concepción ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (709, 'mun_93 ', 'San Andrés Semetabaj ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (710, 'mun_94 ', 'Panajachel ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (711, 'mun_95 ', 'Santa Catarina Palopó ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (712, 'mun_96 ', 'San Antonio Palopó ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (713, 'mun_97 ', 'San Lucas Tolimán ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (714, 'mun_98 ', 'Santa Cruz La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (715, 'mun_99 ', 'San Pablo La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (716, 'mun_100 ', 'San Marcos La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (717, 'mun_101 ', 'San Juan La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (718, 'mun_102 ', 'San Pedro La Laguna ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (719, 'mun_103 ', 'Santiago Atitlán ', 700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (801, 'mun_104 ', 'Totonicapán ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (802, 'mun_105 ', 'San Cristóbal Totonicapán ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (803, 'mun_106 ', 'San Francisco El Alto ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (804, 'mun_107 ', 'San Andrés Xecul ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (805, 'mun_108 ', 'Momostenango ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (806, 'mun_109 ', 'Santa María Chiquimula ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (807, 'mun_110 ', 'Santa Lucía La Reforma ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (808, 'mun_111 ', 'San Bartolo Aguas Calientes ', 800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (901, 'mun_112 ', 'Quetzaltenango ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (902, 'mun_113 ', 'Salcajá ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (903, 'mun_114 ', 'Olintepeque ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (904, 'mun_115 ', 'San Carlos Sija ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (905, 'mun_116 ', 'Sibilia ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (906, 'mun_117 ', 'Cabricán ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (907, 'mun_118 ', 'Cajolá ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (908, 'mun_119 ', 'San Miguel Siguilá ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (909, 'mun_120 ', 'San Juan Ostuncalco ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (910, 'mun_121 ', 'San Mateo ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (911, 'mun_122 ', 'Concepción Chiquirichapa ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (912, 'mun_123 ', 'San Martín Sacatepéquez ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (913, 'mun_124 ', 'Almolonga ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (914, 'mun_125 ', 'Cantel ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (915, 'mun_126 ', 'Huitán ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (916, 'mun_127 ', 'Zunil ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (917, 'mun_128 ', 'Colomba ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (918, 'mun_129 ', 'San Francisco La Unión ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (919, 'mun_130 ', 'El Palmar ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (920, 'mun_131 ', 'Coatepeque ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (921, 'mun_132 ', 'Génova ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (922, 'mun_133 ', 'Flores Costa Cuca ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (923, 'mun_134 ', 'La Esperanza ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (924, 'mun_135 ', 'Palestina de los Altos ', 900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (65, 'nivel_1', 'Nivel 1', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (66, 'nivel_2', 'Nivel 2', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (67, 'nivel_3', 'Nivel 3', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (68, 'nivel_4', 'Nivel 4', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (69, 'Casa', 'Casa', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (70, 'Oficina', 'Oficina', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (71, 'Ambos', 'Ambos', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1228, 'mun_192 ', 'Río Blanco ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1229, 'mun_193 ', 'San Lorenzo ', 1200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1301, 'mun_194 ', 'Huehuetenango ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1302, 'mun_195 ', 'Chiantla ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1303, 'mun_196 ', 'Malacatancito ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1304, 'mun_197 ', 'Cuilco ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1305, 'mun_198 ', 'Nentón ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1306, 'mun_199 ', 'San Pedro Necta ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1307, 'mun_200 ', 'Jacaltenango ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1308, 'mun_201 ', 'Soloma ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1, 'F', 'Femenino', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2, 'M', 'Masculino', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (3, 'S', 'Si', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (4, 'N', 'No', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (5, 'NOSE', 'No sé', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (6, 'NO_SEGURO', 'No estoy seguro/a', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (7, 'ubi_1', 'Campus Central UVG', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (8, 'ubi_2', 'Campus Sololá', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (9, 'ubi_3', 'Campus Sur', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (37, 'ubi_4', 'Colegio Americano', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (10, 'ocup_1', 'Estudiante ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (11, 'ocup_2', 'Catedrático horario', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (12, 'ocup_3', 'Catedrático con plaza fija', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (13, 'ocup_4', 'Investigador/profesional en laboratorio', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (14, 'ocup_5', 'Investigador/profesional en el campo ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (15, 'ocup_6', 'Director/jefe administrativo ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (16, 'ocup_7', 'Técnico de campo ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (17, 'ocup_8', 'Técnico de laboratorio', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (18, 'ocup_9', 'IT/programador/Analista de datos ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (19, 'ocup_10', 'Asistente administrativo ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (20, 'ocup_11', 'Empleado cafetería', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (21, 'ocup_12', 'Conserje', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (22, 'ocup_13', 'Jardinero', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (23, 'ocup_14', 'Guardia de Seguridad', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (36, 'ocup_15', 'Empleado de construcción CIIT', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (24, 'personas_0 ', 'Ninguna persona', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (25, 'personas_1 ', '1 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (26, 'personas_2 ', '2 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (27, 'personas_3 ', '3 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (28, 'personas_4 ', '4 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (29, 'personas_5 ', '5 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (30, 'personas_6 ', '6 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (31, 'personas_7 ', '7 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (32, 'personas_8 ', '8 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (33, 'personas_9 ', '9 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (34, 'personas_10 ', '10 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (35, 'personas_11 ', 'Mas de 10 personas', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (38, 'nose_covid', 'Me han realizado la prueba pero desconozco el resultado', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (64, 'no_se', 'No se', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (99, 'text', '', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (100, 'dep_1 ', 'Guatemala ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (200, 'dep_2 ', 'El Progreso ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (300, 'dep_3 ', 'Sacatepéquez ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (400, 'dep_4 ', 'Chimaltenango ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (500, 'dep_5 ', 'Escuintla ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (600, 'dep_6 ', 'Santa Rosa ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (700, 'dep_7 ', 'Sololá ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (800, 'dep_8 ', 'Totonicapán ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (900, 'dep_9 ', 'Quetzaltenango ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1000, 'dep_10 ', 'Suchitepéquez ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1100, 'dep_11 ', 'Retalhuleu ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1200, 'dep_12 ', 'San Marcos ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1300, 'dep_13 ', 'Huehuetenango ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1400, 'dep_14 ', 'Quiché ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1500, 'dep_15 ', 'Baja Verapaz ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1600, 'dep_16 ', 'Alta Verapaz ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1700, 'dep_17 ', 'Petén ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1800, 'dep_18 ', 'Izabal ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1900, 'dep_19 ', 'Zacapa ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2000, 'dep_20 ', 'Chiquimula ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2100, 'dep_21 ', 'Jalapa ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2200, 'dep_22 ', 'Jutiapa ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (39, 'zon_1 ', 'Zona 1 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (40, 'zon_2 ', 'Zona 2 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (41, 'zon_3 ', 'Zona 3 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (42, 'zon_4 ', 'Zona 4 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (43, 'zon_5 ', 'Zona 5 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (44, 'zon_6 ', 'Zona 6 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (45, 'zon_7 ', 'Zona 7 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (46, 'zon_8 ', 'Zona 8 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (47, 'zon_9 ', 'Zona 9 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (48, 'zon_10 ', 'Zona 10 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (49, 'zon_11 ', 'Zona 11 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (50, 'zon_12 ', 'Zona 12 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (51, 'zon_13 ', 'Zona 13 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (52, 'zon_14 ', 'Zona 14 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (53, 'zon_15 ', 'Zona 15 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1309, 'mun_202 ', 'San Idelfonso Ixtahuacán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1310, 'mun_203 ', 'Santa Bárbara ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1311, 'mun_204 ', 'La Libertad ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1312, 'mun_205 ', 'La Democracia ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1313, 'mun_206 ', 'San Miguel Acatán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1314, 'mun_207 ', 'San Rafael La Indepencia ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1315, 'mun_208 ', 'Todos Santos Cuchumatán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1316, 'mun_209 ', 'San Juan Atitán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1317, 'mun_210 ', 'Santa Eulalia ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1318, 'mun_211 ', 'San Mateo Ixtatán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (54, 'zon_16 ', 'Zona 16 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (55, 'zon_17 ', 'Zona 17 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (56, 'zon_18 ', 'Zona 18 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (57, 'zon_19 ', 'Zona 19 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (58, 'zon_20 ', 'Zona 20 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (59, 'zon_21 ', 'Zona 21 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (60, 'zon_22 ', 'Zona 22 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (61, 'zon_23 ', 'Zona 23 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (62, 'zon_24 ', 'Zona 24 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (63, 'zon_25 ', 'Zona 25 ', 0);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1319, 'mun_212 ', 'Colotenango ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1320, 'mun_213 ', 'San Sebastián Huehuetenango ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1321, 'mun_214 ', 'Tectitán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1322, 'mun_215 ', 'Concepción Huista ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1323, 'mun_216 ', 'San Juan Ixcoy ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1324, 'mun_217 ', 'San Antonio Huista ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1325, 'mun_218 ', 'San Sebastián Coatán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1326, 'mun_219 ', 'Barillas ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1327, 'mun_220 ', 'Aguacatán ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1328, 'mun_221 ', 'San Rafael Pétzal ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1329, 'mun_222 ', 'San Gaspar Ixchil ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1330, 'mun_223 ', 'Santiago Chimaltenango ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1331, 'mun_224 ', 'Santa Ana Huista ', 1300);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1401, 'mun_225 ', 'Santa Cruz del Quiché ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1402, 'mun_226 ', 'Chiché ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1403, 'mun_227 ', 'Chinique ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1404, 'mun_228 ', 'Zacualpa ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1405, 'mun_229 ', 'Chajul ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1406, 'mun_230 ', 'Chichicastenango ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1407, 'mun_231 ', 'Patzité ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1408, 'mun_232 ', 'San Antonio Ilotenango ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1409, 'mun_233 ', 'San Pedro Jocopilas ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1410, 'mun_234 ', 'Cunén ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1411, 'mun_235 ', 'San Juan Cotzal ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1412, 'mun_236 ', 'Joyabaj ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1413, 'mun_237 ', 'Nebaj ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1414, 'mun_238 ', 'San Andrés Sajcabajá ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1415, 'mun_239 ', 'Uspantán ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1416, 'mun_240 ', 'Sacapulas ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1417, 'mun_241 ', 'San Bartolomé Jocotenango ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1418, 'mun_242 ', 'Canillá ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1419, 'mun_243 ', 'Chicamán ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1420, 'mun_244 ', 'Playa Grande -Ixcán ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1421, 'mun_245 ', 'Pachalum ', 1400);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1501, 'mun_246 ', 'Salamá ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1502, 'mun_247 ', 'San Miguel Chicaj ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1503, 'mun_248 ', 'Rabinal ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1504, 'mun_249 ', 'Cubulco ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1505, 'mun_250 ', 'Granados ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1506, 'mun_251 ', 'El Chol ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1507, 'mun_252 ', 'San Jerónimo ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1508, 'mun_253 ', 'Purulhá ', 1500);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1601, 'mun_254 ', 'Cobán ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1602, 'mun_255 ', 'Santa Cruz Verapaz ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1603, 'mun_256 ', 'San Cristóbal Verapaz ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1604, 'mun_257 ', 'Tactic ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1605, 'mun_258 ', 'Tamahú ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1606, 'mun_259 ', 'Tucurú ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1607, 'mun_260 ', 'Panzós ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1608, 'mun_261 ', 'Senahú ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1609, 'mun_262 ', 'San Pedro Carchá ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1610, 'mun_263 ', 'San Juan Chamelco ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1611, 'mun_264 ', 'Lanquín ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1612, 'mun_265 ', 'Cahabón ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1613, 'mun_266 ', 'Chisec ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1614, 'mun_267 ', 'Chahal ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1615, 'mun_268 ', 'Fray Bartolomé de las Casas ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1616, 'mun_269 ', 'La Tinta ', 1600);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1701, 'mun_270 ', 'Flores ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1702, 'mun_271 ', 'San José ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1703, 'mun_272 ', 'San Benito ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1704, 'mun_273 ', 'San Andrés ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1705, 'mun_274 ', 'La Libertad ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1706, 'mun_275 ', 'San Francisco ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1707, 'mun_276 ', 'Santa Ana ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1708, 'mun_277 ', 'Dolores ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1709, 'mun_278 ', 'San Luis ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1710, 'mun_279 ', 'Sayaxché ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1711, 'mun_280 ', 'Melchor de Mencos ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1712, 'mun_281 ', 'Poptún ', 1700);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1801, 'mun_282 ', 'Puerto Barrios ', 1800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1802, 'mun_283 ', 'Livingston ', 1800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1803, 'mun_284 ', 'El Estor ', 1800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1804, 'mun_285 ', 'Morales ', 1800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1805, 'mun_286 ', 'Los Amates ', 1800);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1901, 'mun_287 ', 'Zacapa ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1902, 'mun_288 ', 'Estanzuela ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1903, 'mun_289 ', 'Río Hondo ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1904, 'mun_290 ', 'Gualán ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1905, 'mun_291 ', 'Teculután ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1906, 'mun_292 ', 'Usumatlán ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1907, 'mun_293 ', 'Cabañas ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1908, 'mun_294 ', 'San Diego ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1909, 'mun_295 ', 'La Unión ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (1910, 'mun_296 ', 'Huité ', 1900);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2001, 'mun_297 ', 'Chiquimula ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2002, 'mun_298 ', 'San José La Arada ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2003, 'mun_299 ', 'San Juan Ermita ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2004, 'mun_300 ', 'Jocotán ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2005, 'mun_301 ', 'Camotán ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2006, 'mun_302 ', 'Olopa ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2007, 'mun_303 ', 'Esquipulas ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2008, 'mun_304 ', 'Concepción Las Minas ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2009, 'mun_305 ', 'Quetzaltepeque ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2010, 'mun_306 ', 'San Jacinto ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2011, 'mun_307 ', 'Ipala ', 2000);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2101, 'mun_308 ', 'Jalapa ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2102, 'mun_309 ', 'San Pedro Pinula ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2103, 'mun_310 ', 'San Luis Jilotepeque ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2104, 'mun_311 ', 'San Manuel Chaparrón ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2105, 'mun_312 ', 'San Carlos Alzatate ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2106, 'mun_313 ', 'Monjas ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2107, 'mun_314 ', 'Mataquescuintla ', 2100);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2201, 'mun_315 ', 'Jutiapa ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2202, 'mun_316 ', 'El Progreso ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2203, 'mun_317 ', 'Santa Catarina Mita ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2204, 'mun_318 ', 'Agua Blanca ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2205, 'mun_319 ', 'Asunción Mita ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2206, 'mun_320 ', 'Yupiltepeque ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2207, 'mun_321 ', 'Atescatempa ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2208, 'mun_322 ', 'Jerez ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2209, 'mun_323 ', 'El Adelanto ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2210, 'mun_324 ', 'Zapotitlán ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2211, 'mun_325 ', 'Comapa ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2212, 'mun_326 ', 'Jalpatagua ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2213, 'mun_327 ', 'Conguaco ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2214, 'mun_328 ', 'Moyuta ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2215, 'mun_329 ', 'Pasaco ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2216, 'mun_330 ', 'San José Acatempa ', 2200);
INSERT INTO public.answers (id, code, description, id_father) VALUES (2217, 'mun_331 ', 'Quesada ', 2200);