create table questions
(
    id               bigserial not null
        constraint questions_pkey
            primary key,
    conditions       integer,
    correlative      integer   not null,
    display          boolean,
    id_father        integer,
    image            varchar(255),
    name             varchar(255),
    required         boolean,
    title            varchar(5000),
    id_question_type bigint    not null
        constraint fkgtlkgdgx66mjappaf23li3f9o
            references question_type
            on delete cascade,
    id_questionnaire bigint    not null
        constraint fk6lr5qgf8nw2tpnv25f6ys58st
            references questionnaire_type
            on delete cascade,
    id_sections      bigint    not null
        constraint fkpe0hhdiijj00s97m9ac2imlda
            references sections
            on delete cascade
);

alter table questions
    owner to postgres;

INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (9, 0, 2, true, 8, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Municipio', true, 'Municipio', 3, 2, 10);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (68, 7, 4, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_1', true, 'Edificio A', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (69, 7, 5, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_2', true, 'Edificio C', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (70, 7, 6, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_3', true, 'Edificio C1 Labs microbiologia', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (95, 8, 30, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_27', true, 'Edificio Central Sololá', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (96, 8, 31, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_28', true, 'Parqueo', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (97, 9, 32, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_29', true, 'Edificio Central Campus sur', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (98, 9, 33, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_30', true, 'Parqueo', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (99, 37, 34, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_31', true, 'Comedor Colegio Americano', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (100, 37, 35, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_32', true, 'Parqueo', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (101, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/Localidad.svg', 'Titulo_Seccion_2', true, 'DOMICILIO', 1, 2, 10);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (71, 7, 7, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_4', true, 'Edificio D comedor de mantenimiento e invernadero.', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (72, 7, 8, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_5', true, 'Edificio E', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (73, 7, 9, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_6', true, 'Edificio F', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (74, 7, 10, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_7', true, 'Edificio G', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (75, 7, 11, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_8', true, 'Edificio H', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (76, 7, 12, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_9', true, 'Edificio I', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (77, 7, 13, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_10', true, 'Edificio J', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (78, 7, 14, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_11', true, 'Edificio J1 Aula virtual', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (79, 7, 15, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_12', true, 'Edificio K', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (80, 7, 16, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_13', true, 'Edificio M insectario', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (81, 7, 17, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_14', true, 'Metal mecánica (área  buses CAG)', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (82, 7, 18, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_15', true, 'Laboratorio Materiales II (área de buses CAG)', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (83, 7, 19, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_16', true, 'Parqueo 1', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (84, 7, 20, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_17', true, 'Edificio II1', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (85, 7, 21, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_18', true, 'Edificio II2', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (86, 7, 22, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_19', true, 'Casita Roja', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (16, 0, 6, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Arritmia_cardiaca', false, 'Arritmia cardiaca', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (87, 7, 23, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_20', true, 'Garitas 5, 6, 7, 8 y 9', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (88, 7, 24, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_21', true, 'Vida Silvestre Biología/ Centro de estudios ambientales (atrás del gimnasio Wilson del CAG).', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (89, 7, 25, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_22', true, 'Casa VIH externa', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (90, 7, 26, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_23', true, 'Casa Financiera externa', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (91, 7, 27, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_24', true, 'Casa Proyectos externa', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (92, 7, 28, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_25', true, 'Casa Administrativa', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (93, 7, 29, true, 6, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion_26', true, 'Casa CIE.', 6, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (6, 0, 6, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion', true, '¿En que campus se ubica?', 3, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (67, 7, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ubicacion', true, '¿Lugar de trabajo?', 7, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (10, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Zona', true, 'Zona', 3, 2, 10);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (102, 0, 18, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'tiempo_comida', true, '¿Ha obviado un tiempo de comida?', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (1, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/DatosGenerales.svg', 'Titulo_Seccion_1', true, 'DATOS GENERALES', 1, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (2, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'telefono', true, 'Telefono', 4, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (3, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Fecha_nac', true, 'Fecha de Nacimiento', 2, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (4, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Sexo', true, 'Sexo', 3, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (5, 0, 5, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Ocupacion', false, 'Ocupación', 3, 2, 1);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (94, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/DatosGenerales.svg', 'Titulo_Seccion_9', true, 'UBICACIÓN EN SU CAMPUS', 1, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (7, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/Localidad.svg', 'Titulo_Seccion_2', true, 'DOMICILIO', 1, 2, 2);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (8, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Departamento', true, 'Departamento', 3, 2, 2);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (11, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/Afecciones.svg', 'Titulo_Seccion_3', true, 'HISTORIAL MÉDICO', 1, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (12, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'afeccion_medica', false, '¿Tiene alguna de las siguientes enfermedades?', 7, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (13, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Diabetes', false, 'Diabetes', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (14, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Hipertension_arterial', false, 'Hipertensión arterial', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (15, 0, 5, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Insuficiencia_cardiaca', false, 'Insuficiencia cardiaca', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (17, 0, 7, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Cardiopatia_congestiva', false, 'Cardiopatía congestiva', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (18, 0, 8, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Angina_pecho', false, 'Angina de pecho', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (19, 0, 9, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Hipertension_pulmunar', false, 'Hipertensión pulmunar', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (20, 0, 10, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'EPOC', false, 'Enfermedad pulmonar obstructiva crónica (EPOC) ', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (21, 0, 11, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Enfisema_pulmonar', false, 'Enfisema pulmonar', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (22, 0, 12, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Asma', false, 'Asma', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (29, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/Convivientes.svg', 'Titulo_Seccion_4', true, 'CONVIVENCIA EN CASA', 1, 2, 4);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (30, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'personas_casa', true, '¿Cuantas personas viven contigo en casa?', 3, 2, 4);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (31, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'mayor_60', true, '¿Hay alguna persona >60 años?', 3, 2, 4);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (32, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'menor_12', true, '¿Hay algún niño <12 años?', 3, 2, 4);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (33, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/Transporte.svg', 'Titulo_Seccion_5', true, 'MOVILIZACION Y DESPLAZO', 1, 2, 5);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (34, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'transporte_uvg', true, 'Para movilizarte a UVG, te movilizas por:', 7, 2, 5);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (36, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'transporte_uvg_2', true, 'Transporte público', 6, 2, 5);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (103, 0, 36, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'nivel', true, 'Nivel', 3, 2, 9);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (24, 0, 15, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'CANCER', false, 'CANCER', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (104, 0, 13, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Enfermedad_cardiaca', false, 'Alguna enfermedad del corazón', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (25, 0, 16, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'VIH', false, 'VIH', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (26, 0, 17, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Inmunodeficiencia_congénita', false, 'Inmunodeficiencia congénita', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (27, 0, 18, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Transplante_organo', false, 'Transplante de órgano', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (28, 0, 19, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'corticoesteroideos', false, 'Uso crónico de medicamentos corticoesteroideos', 6, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (23, 0, 14, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'afeccion_medica_inmunodeficiencia', false, '¿Tiene alguna condición médica que debilite su sistema inmunológico?', 7, 2, 3);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (35, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'transporte_uvg_1', true, 'Transporte propio', 6, 2, 5);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (38, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/TrabajadorSalud.svg', 'Titulo_Seccion_6', true, 'OCUPACIONES DE RIESGO', 1, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (44, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/DatosGenerales.svg', 'Titulo_Seccion_7', true, 'MI REPORTE DIARIO', 1, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (46, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'sintomas', true, 'En las últimas 24 hrs, ¿has tenido alguno de estos síntomas? Marca todos los que apliquen.', 7, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (47, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'fiebre', true, 'Fiebre (mayor a 38 grados celsius)', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (48, 0, 5, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Tos', true, 'Tos (si usualmente tienes tos, ¿ha empeorado?)', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (49, 0, 6, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Rinorrea', true, 'Rinorrea (secreciones nasales/Salida de material líquido-mucoso por la nariz)', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (50, 0, 7, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'garganta', true, 'Dolor de garganta', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (51, 0, 8, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'respirar', true, 'Dificultad para respirar', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (52, 0, 9, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'Diarrea', true, 'Diarrea ', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (53, 0, 10, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'vomitos', true, 'Vómitos ', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (54, 0, 11, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'escalofrios', true, 'Escalofríos', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (55, 0, 12, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'dolor_cuerpo', true, 'Dolor de cuerpo', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (56, 0, 13, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ocular', true, 'Ojos rojos o dolor ocular', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (57, 0, 14, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'general', true, 'Malestar general', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (58, 0, 15, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'olfato', true, 'Pérdida o disminución del sentido del olfato', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (59, 0, 16, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'gusto', true, 'Pérdida o disminución del sentido del gusto', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (60, 0, 17, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'dedos', true, 'Dedos de los pies rojos o inflamados', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (63, 0, 20, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'contacto_2m', true, 'En las últimas 24 hrs, aproximadamente con cuántas personas fuera de tu vivienda has tenido contacto (a una distancia de 2 mts o menos)?', 3, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (64, 0, 1, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/DatosGenerales.svg', 'Titulo_Seccion_8', true, 'REPORTE CONVIVIENTE', 1, 1, 8);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (66, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'positivo_covid_conviviente', true, 'En las últimas 24 hrs, alguien (que no seas tú) en tu vivienda ¿ha tenido un resultado de prueba POSITIVO para COVID-19?', 3, 1, 8);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (65, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'sintomas_conviviente', true, 'En las últimas 24 horas, alguien (que no seas tú) en tu hogar  ha tenido: ¿Dificultad para respirar, diarrea,  vómitos, Escalofríos, dolor de cuerpo, ojos rojos o dolor ocular, malestar general, pérdida o disminución del sentido del olfato, pérdida o disminución del sentido del gusto, dolor de garganta, secreción nasal, tos persistente, fiebre, dedos de los pies inflamados y enrojecidos, ha obviado un tiempo de comida?', 3, 1, 8);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (61, 0, 19, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'ninguno', true, 'Ninguno de los anteriores', 6, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (62, 0, 20, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'positivo_covid', true, 'En las últimas 24 hrs, ¿has tenido un resultado de prueba POSITIVO para COVID-19?', 3, 1, 7);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (37, 0, 5, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'transporte_uvg_3', true, 'Transporte institucional / empresa', 6, 2, 5);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (40, 0, 3, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'atencion_salud', true, '¿Trabajas en actividades de atención de salud?', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (41, 0, 4, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'atencion_clientes', true, '¿Tienes contacto permanente con clientes?', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (39, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'trabajo_casa', true, '¿Cuál es tu modalidad de trabajo? ', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (42, 0, 5, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'atencion_desechos', true, '¿Tienes contacto con pertenencias o desechos de otras personas?', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (105, 0, 6, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'atencion_biologicas', true, '¿Trabajas manejando o procesando muestras biológicas de animales o humanas?', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (43, 0, 7, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'comparte_oficina', true, '¿Compartes tu oficina?', 3, 2, 6);
INSERT INTO public.questions (id, conditions, correlative, display, id_father, image, name, required, title, id_question_type, id_questionnaire, id_sections) VALUES (45, 0, 2, true, 0, 'https://app-covid19-uvg.herokuapp.com/images/uvg.png', 'trabajar_estudiar', true, '¿En las últimas 24 hrs, te presentaste a trabajar o estudiar al campus o estación de campo correspondiente?', 3, 1, 7);